export const data = [
	{
		agencyId: 'guardian',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA',
		firstName: 'Aimee',
		lastName: 'Hesser',
		preferredName: 'Buesnel',
		employmentStatus: 'inactive',
		gender: 'F',
		dateOfBirth: '1995-11-06',
		socialSecurityNumber: '296-87-2365',
		email: 'abuesnel0@wikipedia.org',
		phoneNumber: '+17132147178',
		address1: '2965 Straubel Pass',
		address2: null,
		city: 'Houston',
		stateCode: 'TX',
		zipCode: '77281',
	},
	{
		agencyId: 'guardia',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA', // test agency id -> expecting 401 response for bad id
		firstName: 'Aimee',
		lastName: 'Hesser',
		preferredName: 'Buesnel',
		employmentStatus: 'inactive',
		gender: 'F',
		dateOfBirth: '1995-11-06',
		socialSecurityNumber: '296-87-2365',
		email: 'abuesnel0@wikipedia.org',
		phoneNumber: '+17132147178',
		address1: '2965 Straubel Pass',
		address2: null,
		city: 'Houston',
		stateCode: 'TX',
		zipCode: '77281',
	},
	{
		agencyId: 'guardian',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA',
		firstName: 3, // should be 'string' -> 401 response for wrong type
		lastName: 'Hesser',
		preferredName: 'Buesnel',
		employmentStatus: 'inactive',
		gender: 'F',
		dateOfBirth: '1995-11-06',
		socialSecurityNumber: '296-87-2365',
		email: 'abuesnel0@wikipedia.org',
		phoneNumber: '+17132147178',
		address1: '2965 Straubel Pass',
		address2: null,
		city: 'Houston',
		stateCode: 'TX',
		zipCode: '77281',
	},
	{
		agencyId: 'guardian',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA',
		firstName: 'Aimee',
		lastName: 'Hesser0001Hesser0001Hesser0001Hesser0001Hesser00012', // too long -> expecting 401 for too long string.
		preferredName: 'Buesnel',
		employmentStatus: 'inactive',
		gender: 'F',
		dateOfBirth: '1995-11-06',
		socialSecurityNumber: '296-87-2365',
		email: 'abuesnel0@wikipedia.org',
		phoneNumber: '+17132147178',
		address1: '2965 Straubel Pass',
		address2: null,
		city: 'Houston',
		stateCode: 'TX',
		zipCode: '77281',
	},
	{
		agencyId: 'guardian',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA',
		firstName: 'Aimee',
		lastName: 'Hesser',
		preferredName: 3, // should be string or null -> expecting 401
		employmentStatus: 'inactive',
		gender: 'F',
		dateOfBirth: '1995-11-06',
		socialSecurityNumber: '296-87-2365',
		email: 'abuesnel0@wikipedia.org',
		phoneNumber: '+17132147178',
		address1: '2965 Straubel Pass',
		address2: null,
		city: 'Houston',
		stateCode: 'TX',
		zipCode: '77281',
	},
	{
		agencyId: 'guardian',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA',
		firstName: 'Aimee',
		lastName: 'Hesser',
		preferredName: 'Buesnel',
		employmentStatus: 'terminated', // not an allowed employment status -> expecting 401
		gender: 'F',
		dateOfBirth: '1995-11-06',
		socialSecurityNumber: '296-87-2365',
		email: 'abuesnel0@wikipedia.org',
		phoneNumber: '+17132147178',
		address1: '2965 Straubel Pass',
		address2: null,
		city: 'Houston',
		stateCode: 'TX',
		zipCode: '77281',
	},
	{
		agencyId: 'guardian',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA',
		firstName: 'Aimee',
		lastName: 'Hesser',
		preferredName: 'Buesnel',
		employmentStatus: 'inactive',
		gender: 'X', // should be F, M, or null -> expecting 401
		dateOfBirth: '1995-11-06',
		socialSecurityNumber: '296-87-2365',
		email: 'abuesnel0@wikipedia.org',
		phoneNumber: '+17132147178',
		address1: '2965 Straubel Pass',
		address2: null,
		city: 'Houston',
		stateCode: 'TX',
		zipCode: '77281',
	},
	{
		agencyId: 'guardian',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA',
		firstName: 'Aimee',
		lastName: 'Hesser',
		preferredName: 'Buesnel',
		employmentStatus: 'inactive',
		gender: 'F',
		dateOfBirth: undefined, // omitted from JSON -> expecting 401 for missing field
		socialSecurityNumber: '296-87-2365',
		email: 'abuesnel0@wikipedia.org',
		phoneNumber: '+17132147178',
		address1: '2965 Straubel Pass',
		address2: null,
		city: 'Houston',
		stateCode: 'TX',
		zipCode: '77281',
	},
	{
		agencyId: 'guardian',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA',
		firstName: 'Aimee',
		lastName: 'Hesser',
		preferredName: 'Buesnel',
		employmentStatus: 'inactive',
		gender: 'F',
		dateOfBirth: '1995-11-06',
		socialSecurityNumber: '296872365', // wrong SSN format -> expecting 401
		email: 'abuesnel0@wikipedia.org',
		phoneNumber: '+17132147178',
		address1: '2965 Straubel Pass',
		address2: null,
		city: 'Houston',
		stateCode: 'TX',
		zipCode: '77281',
	},
	{
		agencyId: 'guardian',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA',
		firstName: 'Aimee',
		lastName: 'Hesser',
		preferredName: 'Buesnel',
		employmentStatus: 'inactive',
		gender: 'F',
		dateOfBirth: '1995-11-06',
		socialSecurityNumber: '296-87-2365',
		email: 'not-an-email', // invalid email -> expecting 401
		phoneNumber: '+17132147178',
		address1: '2965 Straubel Pass',
		address2: null,
		city: 'Houston',
		stateCode: 'TX',
		zipCode: '77281',
	},
	{
		agencyId: 'guardian',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA',
		firstName: 'Aimee',
		lastName: 'Hesser',
		preferredName: 'Buesnel',
		employmentStatus: 'inactive',
		gender: 'F',
		dateOfBirth: '1995-11-06',
		socialSecurityNumber: '296-87-2365',
		email: 'abuesnel0@wikipedia.org',
		phoneNumber: '17132147178', // missing leading + -> expecting 401
		address1: '2965 Straubel Pass',
		address2: null,
		city: 'Houston',
		stateCode: 'TX',
		zipCode: '77281',
	},
	{
		agencyId: 'guardian',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA',
		firstName: 'Aimee',
		lastName: 'Hesser',
		preferredName: 'Buesnel',
		employmentStatus: 'inactive',
		gender: 'F',
		dateOfBirth: '1995-11-06',
		socialSecurityNumber: '296-87-2365',
		email: 'abuesnel0@wikipedia.org',
		phoneNumber: '+17132147178',
		address1: '', // empty address -> expecting 401
		address2: null,
		city: 'Houston',
		stateCode: 'TX',
		zipCode: '77281',
	},
	{
		agencyId: 'guardian',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA',
		firstName: 'Aimee',
		lastName: 'Hesser',
		preferredName: 'Buesnel',
		employmentStatus: 'inactive',
		gender: 'F',
		dateOfBirth: '1995-11-06',
		socialSecurityNumber: '296-87-2365',
		email: 'abuesnel0@wikipedia.org',
		phoneNumber: '+17132147178',
		address1: '2965 Straubel Pass',
		address2: 3, // should be string or null -> expecting 401
		city: 'Houston',
		stateCode: 'TX',
		zipCode: '77281',
	},
	{
		agencyId: 'guardian',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA',
		firstName: 'Aimee',
		lastName: 'Hesser',
		preferredName: 'Buesnel',
		employmentStatus: 'inactive',
		gender: 'F',
		dateOfBirth: '1995-11-06',
		socialSecurityNumber: '296-87-2365',
		email: 'abuesnel0@wikipedia.org',
		phoneNumber: '+17132147178',
		address1: '2965 Straubel Pass',
		address2: null,
		city: '', // empty city -> expecting 401
		stateCode: 'TX',
		zipCode: '77281',
	},
	{
		agencyId: 'guardian',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA',
		firstName: 'Aimee',
		lastName: 'Hesser',
		preferredName: 'Buesnel',
		employmentStatus: 'inactive',
		gender: 'F',
		dateOfBirth: '1995-11-06',
		socialSecurityNumber: '296-87-2365',
		email: 'abuesnel0@wikipedia.org',
		phoneNumber: '+17132147178',
		address1: '2965 Straubel Pass',
		address2: null,
		city: 'Houston',
		stateCode: 'TEX', // state code must be two characters -> expecting 401
		zipCode: '77281',
	},
	{
		agencyId: 'guardian',
		agencyName: 'Guardian Home Care',
		employmentType: 'W_2',
		jobTitle: 'PCA',
		firstName: 'Aimee',
		lastName: 'Hesser',
		preferredName: 'Buesnel',
		employmentStatus: 'inactive',
		gender: 'F',
		dateOfBirth: '1995-11-06',
		socialSecurityNumber: '296-87-2365',
		email: 'abuesnel0@wikipedia.org',
		phoneNumber: '+17132147178',
		address1: '2965 Straubel Pass',
		address2: null,
		city: 'Houston',
		stateCode: 'TX',
		zipCode: '1234', // ZIP code is too short -> expecting 401
	},
];
